# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="audio-b6f8c56a-f336-49f7-8256-bee9156657aa.mp3"
Content-Type: audio/mpeg

< ./audio-b6f8c56a-f336-49f7-8256-bee9156657aa.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription

POST http://localhost:3333/videos/9ac39266-e3b6-4918-81d1-60e70e301750/transcription
Content-Type: application/json

{
    "prompt": "nmap, network mapper"
}

###

# @name generate_ai_completion

POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "b9aede3a-a3fb-4f82-bfef-17f3d6f86b94",
    "temperature": 0.5,
    "prompt": "Gere um resumo sucinto da transcrição do video informada a seguir: '''{transcription}'''"
}

